---
base_sshd_allow_agent_forwarding: "yes"
base_sshd_allow_tcp_forwarding: "no"
base_sshd_allow_password_authentication: "yes"
base_sshd_permit_root_login: "prohibit-password"
base_sshd_permit_tunnel: "no"
base_sshd_x11_forwarding: "no"
base_sshd_banner: ""

timezone_zone: Europe/Berlin

locales_present:
  - en_US.UTF-8
  - de_DE.UTF-8

locales_language_packs_present:
  - language-pack-en
  - language-pack-en-base
  - language-pack-de
  - language-pack-de-base

locales_absent: []

locales_language_packs_absent: []

postfix_aliases:
  - user: root 
    alias: admin@crylle.net 
postfix_virtual_aliases:
  - virtual: "@{{ ansible_fqdn }}"
    alias: root
postfix_mydestination:
  - "{{ postfix_hostname }}"
  - localhost
postfix_inet_interfaces: loopback-only
postfix_relayhost: smtp.crylle.local
postfix_relayhost_port: 25
