---
unattended_origins_patterns:
  - '${distro_id}:${distro_codename}'
  - '${distro_id}:${distro_codename}-updates'
  - '${distro_id}:${distro_codename}-security'
  - '${distro_id}ESM:${distro_codename}-infra-security'
  - '${distro_id}ESMApps:${distro_codename}-apps-security'
  - '${distro_id}:${distro_codename}-proposed-updates'

packages_os:
  - landscape-common
  - update-notifier-common
  - systemd-timesyncd

services_disabled:
  - ModemManager
  - snapd.service
  - snapd.socket
  - snapd.seeded.service
  - iscsid.service
  - iscsid.socket
  - multipathd
  - avahi-daemon
  - bluetooth.service
