---
- name: "reloading syslog"
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: "reloading systemd-timesyncd"
  service:
    name: systemd-timesyncd
    state: restarted
    enabled: yes

