---
- name: "reload syslog"
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: "reload autofs"
  service:
    name: autofs
    state: restarted
    enabled: yes

- name: "reload systemd-timesyncd"
  service:
    name: systemd-timesyncd
    state: restarted
    enabled: yes

