---
- hosts: localhost
  tags: always
  become: true

  vars:
    ansible_pull_url: https://github.com/cr9427/ansible.git

  pre_tasks:
    - name: "print some vars"
      tags: debug
      debug:
        var: >
          ansible_virtualization_type,
          ansible_distribution,
          ansible_distribution_release

    - name: "update repository cache on Debian based"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: all
  tags: base
  become: true
  roles:
    - base
    - oefenweb.timezone
    - oefenweb.locales
    - oefenweb.postfix
    - hifis.unattended_upgrades
    - robertdebock.bootstrap
    - robertdebock.autofs
