---
- hosts: localhost
  tags: always
  become: true
  pre_tasks:

  - name: "print some vars"
    tags: debug
    debug:
      var: ansible_virtualization_type, ansible_distribution

  - name: "update repository cache on Debian based"
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: localhost
  tags: base
  become: true
  gather_facts: false
  roles:
    - base

- hosts: crylle
  tags: crylle
  become: true
  gather_facts: false
  roles:
    - crylle

- hosts: workstations
  tags: crylle
  become: true
  gather_facts: false
  roles:
    - workstations
