---
- hosts: all
  become: true
  pre_tasks:
    - name: Print some variables"
      tags:
        - always
      debug:
        var: >
          ansible_virtualization_type,
          ansible_distribution,
          ansible_distribution_release

    - name: Create groups based on the distibution type
      tags:
        - always
      group_by:
        key: "{{ ansible_distribution }}"
      changed_when: false

    - name: Update repository cache on Debian based systems
      apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

#  - name: update repository cache on CentOS
#    dnf:
#      update_cache: yes
#    changed_when: false
#    when: ansible_distribution == "CentOS"

  roles:
    - base
    - oefenweb.timezone
    - oefenweb.locales
    - oefenweb.postfix
    - hifis.unattended_upgrades
    - robertdebock.bootstrap
    - robertdebock.autofs

- hosts: crylle
  become: true
  roles:
    - crylle

- hosts: proxmox
  become: true
  roles:
    - proxmox
  tags:
    - proxmox
