---
- name: Reloading apt-cache
  shell:
    cmd: apt update

- name: Reloading networking
  shell:
    cmd: systemctl restart networking.service

- name: Reloading pveproxy
  shell:
    cmd: systemctl restart pveproxy.service
