---
proxmox_nfs_mounts_storageId: 'nas.crylle.local'
proxmox_nfs_mounts_server: 'nas.crylle.local'
proxmox_nfs_mounts_export: '/pve'
proxmox_nfs_mounts_path: '/mnt/pve/nas'
proxmox_nfs_mounts_content: 'vztmpl,rootdir,snippets,iso,backup,images'
proxmox_nfs_mounts_max_protected_backups: '5'
proxmox_nfs_mounts_prune_backups: 'keep-last=3'
