---
proxmox_nfs_mounts_storageId: 'nas.crylle.local'
proxmox_nfs_mounts_server: 'nas.crylle.local'
proxmox_nfs_mounts_export: '/pve'
proxmox_nfs_mounts_path: '/mnt/pve/nas'
proxmox_nfs_mounts_content: 'vztmpl,rootdir,snippets,iso,backup,images'
proxmox_nfs_mounts_max_protected_backups: '5'
proxmox_nfs_mounts_prune_backups: 'keep-last=3'

proxmox_vm_template_image: 'jammy-minimal-cloudimg-amd64.img'
proxmox_vm_template_id: '9100'
proxmox_vm_template_cpu: '2'
proxmox_vm_template_mem: '2048'
proxmox_vm_template_cicustom: 'user=nas.crylle.local:snippets/www-config.yaml'
proxmox_vm_template_vmid: '1000'
