---
proxmox_nfs-mounts_storageId: 'nas'
proxmox_nfs-mounts_server: 'nas'
proxmox_nfs-mounts_export: '/pve'
proxmox_nfs-mounts_content: 'vztmpl,rootdir,snippets,iso,backup,images'
proxmox_nfs-mounts_max-protected-backups: '5'
proxmox_nfs-mounts_prune-backups: 'keep-last=3'
