---
- name: "managing /etc/apt/sources.list.d/ for pve no-subscription"
  template:
    src: "apt/{{ item }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item }}.list"
    backup: yes
    owner: root
    group: root
    mode: 0644
  loop:
    - "pve-enterprise"
    - "pve-no-subscription"
  notify: "reloading apt-cache"
