---
- name: 'configuring interfaces for host {{ ansible_hostname }}'
  tags: proxmox,interfaces
  when: ansible_hostname == 'pve1'
  file:
    src: "interfaces/interfaces.{{ ansible_hostname }}"
    dest: "/etc/network/interfaces"
    backup: true
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify: "reloading networking"
