---
- name: 'creating ubuntu minimal vm template and creating a vm'
  shell:
    chdir: '/tmp'
    cmd: |
      wget https://cloud-images.ubuntu.com/minimal/daily/jammy/current/{{ proxmox_vm_template_image }} -P /tmp
      mv /tmp/{{ proxmox_vm_template_image }} /tmp/{{ proxmox_vm_template_image }}.qcow2
      qemu-img resize /tmp/{{ proxmox_vm_template_image }}.qcow2 32G
      qm destroy {{ proxmox_vm_template_id }}
      qm create {{ proxmox_vm_template_id }} \
        --name ubuntu-22.04-cloudinit --numa 0 --ostype l26 \
        --cpu cputype=host --cores {{ proxmox_vm_template_cpu }} --sockets 1 \
        --memory {{ proxmox_vm_template_mem }}  \
        --net0 virtio,bridge=vmbr0
      qm importdisk {{ proxmox_vm_template_id }} /tmp/{{ proxmox_vm_template_image }}.qcow2 local-lvm
      qm set {{ proxmox_vm_template_id }} --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-{{ proxmox_vm_template_id }}-disk-0,discard=on,ssd=1
      qm set {{ proxmox_vm_template_id }} --ide2 local-lvm:cloudinit
      qm set {{ proxmox_vm_template_id }} --boot c --bootdisk scsi0
      qm set {{ proxmox_vm_template_id }} --serial0 socket --vga serial0
      qm set {{ proxmox_vm_template_id }} --agent enabled=1
      qm set {{ proxmox_vm_template_id }} --ipconfig0 ip=dhcp,ip6=dhcp
      qm set {{ proxmox_vm_template_id }} --cicustom {{ proxmox_vm_template_cicustom }}
      qm template {{ proxmox_vm_template_id }}
      qm clone {{ proxmox_vm_template_id }} {{ proxmox_vm_template_vmid }} \
        -name test \
        --full false \
        --storage local-lvm
      touch /etc/pve/vm_template.configured
    creates: '/etc/pve/vm_template.configured'
