---
- name: "reloading ssh"
  service:
    name: ssh
    state: restarted
    enabled: yes

- name: "reloading postfix"
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: "rebuilding locales database"
  command: dpkg-reconfigure -f noninteractive locales
