---
- name: "install kerberos client" 
  tags: crylle,kerberos
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']
  block:

    - name: "installing package krb5-user"
      apt:
        name: "krb5-user"
        state: latest

    - name: "installing krb5.conf"
      copy:
        src: "kerberos/krb5.conf"
        dest: "/etc/krb5.conf"
        owner: root
        group: root
        mode: 0444
