---
- name: "adding ansible-pull cron job"
  cron:
    name: ansible auto-provision
    user: automator
    minute: "7"
    hour: "*/4"
    job: ansible-pull -o -U https://github.com/cr9427/ansible.git > /dev/null
