---
- name: "adding ansible-pull cron job"
  cron:
    name: ansible auto-provision
    user: automator
    minute: "7"
    hour: "*/4"
    job: >
      ansible-pull
      --url https://github.com/cr9427/ansible.git
      --only-if-changed
      --sleep 10800
      > /dev/null
