---
- name: Adding ansible-pull cron job
  ansible.builtin.cron:
    name: ansible auto-provision
    user: "{{ ansible_pull_user }}"
    minute: "0"
    hour: "*/4"
    job: >
      ansible-pull
      --url {{ ansible_pull_url }}
      --only-if-changed
      --sleep 10800
      --track-subs
      > /dev/null
