---
- name: "specific tasks for Ubuntu"
  tags: base,ubuntu
  when: ansible_distribution in ['Ubuntu']
  block:
  
  - name: "installing specific packages for Ubuntu"
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - "landscape-common"
      - "update-notifier-common"
      - "systemd-timesyncd"

- name: "specific tasks for Pop!_OS"
  tags: base,ubuntu
  when: ansible_distribution in ['Pop!_OS']
  block:
  
  - name: "installing specific packages for Pop!_OS"
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - "landscape-common"

