---
- name: Install {{ ansible_distribution }} specific packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages_os }}"
    - "{{ packages_generic }}"

      #  name: Populate service facts
      #  service_facts:

- name: Disable {{ ansible_distribution }} specific services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  register: unused_disable
  failed_when: "unused_disable is failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg)"
  with_items: "{{ services_disabled }}"

#- name: Tasks for 'Pop!_OS'
#  when:
#    - ansible_distribution in ['Pop!_OS']
#  block:
#    - name: Installing specific packages for Pop!_OS
#      ansible.builtin.apt:
#        name: "{{ item }}"
#        state: latest
#      with_items:
#        - landscape-common
