---
- name: Tasks for Ubuntu
  when:
    - ansible_distribution in ['Ubuntu']
  block:
    - name: Installing specific packages for Ubuntu
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_item:
        - landscape-common
        - update-notifier-common
        - systemd-timesyncd

- name: Tasks for 'Pop!_OS'
  when:
    - ansible_distribution in ['Pop!_OS']
  block:
    - name: Installing specific packages for Pop!_OS
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_item:
        - landscape-common

- name: Tasks for Debian
  when:
    - ansible_distribution in ['Debian']
  block:
    - name: Installing specific packages for Debian
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_item:
        - reboot-notifier
        - systemd-timesyncd
