---
- name: "specific tasks for {{ ansible_distribution }}"
  tags: base,ubuntu
  when: ansible_distribution in ['Ubuntu']
  block:
  
  - name: "installing specific packages for {{ ansible_distribution }}"
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - "landscape-common"
      - "update-notifier-common"
      - "systemd-timesyncd"

- name: "specific tasks for {{ ansible_distribution }}"
  tags: base,ubuntu
  when: ansible_distribution in ['Pop!_OS']
  block:
  
  - name: "installing specific packages for {{ ansible_distribution }}"
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - "landscape-common"

- name: "specific tasks for {{ ansible_distribution }}"
  tags: base,ubuntu
  when: ansible_distribution in ['Debian']
  block:
  
  - name: "installing specific packages for {{ ansible_distribution }}"
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - "reboot-notifier"
      - "systemd-timesyncd"

