---
- name: "specific tasks for Ubuntu"
  tags: base,ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
  
  - name: "install specific packages for Ubuntu"
    apt:
      name: "{{ item }}"
      state: latest
    loop:
      - "landscape-common"
      - "update-notifier-common"
