---
- name: "prepareing and set locale" 
  tags: locale
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']
  block:
    - name: "generating locales"
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ base_locales }}"
      notify: "rebuild locales database"

    - name: "setting the default locale"
      lineinfile:
        dest: /etc/default/locale
        regexp: "^LANG="
        line: "LANG={{ base_locale }}"
      notify: "rebuild locales database"
