---
- name: "prepare and set locale" 
  tags: locale
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']
  block:
    - name: "generate locales"
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ config_system_locales }}"
      notify: "rebuild locales database"

    - name: "set the default locale"
      lineinfile:
        dest: /etc/default/locale
        regexp: "^LANG="
        line: "LANG={{ config_system_locale }}"
      notify: "rebuild locales database"
