---
- import_tasks: roles/base/tasks/swap.yml
- import_tasks: tasks/packages.yml
- import_tasks: roles/base/tasks/virtualization_type.yml
- import_tasks: roles/base/tasks/distribution_type.yml
- import_tasks: roles/base/tasks/ssh.yml
- import_tasks: roles/base/tasks/unattended-upgrades.yml
- import_tasks: roles/base/tasks/locales.yml
- import_tasks: roles/base/tasks/timezone.yml
- import_tasks: roles/base/tasks/users.yml
- import_tasks: roles/base/tasks/cron.yml
