---
- name: "installing and configuring postfix"
  tags: base,mail,postfix
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']
  block:
  - name: "installing postfix package"
    apt:
      name: "postfix"
      state: latest

#  - name: "configuring auto-upgrades settings"
#    copy:
#      src: "unattended-upgrades/21auto-upgrades-local"
#      dest: "/etc/apt/apt.conf.d/21auto-upgrades-local"
#      owner: root
#      group: root
#      mode: 0644
#
#  - name: "generating unatended-upgrades settings from template"
#    template:
#      src: "unattended-upgrades/unattended-upgrades.{{ ansible_distribution }}.j2"
#      dest: "/etc/apt/apt.conf.d/51unattended-upgrades-local"
#      owner: root
#      group: root
#      mode: 0644

