---
- name: "specific tasks to check if swap is available"
  tags: base,swap
#  when: ansible_facts['memory_mb']['swap']['total'] == 0 and ansible_virtualization_role == "host"
  when: ansible_memory_mb['swap']['total'] == 0 and ansible_virtualization_role == "host"
  block:
  
  - name: "installing dphys-swapfile package"
    apt:
      name: "dphys-swapfile"
      state: latest

#  - name: "starting lldpd"
#    service:
#      name: "lldpd"
#      state: started
#      enabled: yes
