---
- name: Is swap available on native host
  when: >
    ansible_memory_mb['swap']['total'] == 0 and
    ansible_virtualization_role == "host" and
    ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']
  apt:
    name: dphys-swapfile
    state: latest
