---
- name: Creating users for automator
  user:
    name: automator"
    uid: 500
    groups: sudo
    system: yes
    create_home: yes

- name: Adding ssh key for user automator
  authorized_key:
    user: automator
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG+ilozyZmL+d2Q2D3dlHiFqxfe994u8YJzGOVN5QSPZ automator@crylle.net

- name: Adding sudoers file for user automator
  copy:
    src: roles/base/files/sudo/automator
    dest: /etc/sudoers.d/automator
    owner: root
    group: root
    mode: 0440

- name: Creating user holm
  when: inventory_hostname not in groups['crylle']
  user:
    name: holm
    uid: 1001
    groups: sudo, adm
    shell: /usr/bin/zsh
    home: /home/holm
    create_home: yes
    password: $6$j9bjDnd.BY8BUs6v$bxi7SLmTd0UIHBPRuyeiVL8Vt4CFBGeXQnlNpUyPhWpu45ZOepXKMXf9LLJLGoZZTt5RXcahmSHaFSihkqXVp1

- name: Adding ssh-key for user holm
  when: inventory_hostname not in groups['crylle']
  authorized_key:
    user: holm
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVtawLHGmKWf8WBPLhqksVCLvLYj+B8fev8QNEk/tVV hk@crylle.net"

- name: Creating ssh-key for root
  shell:
    cmd: "ssh-keygen -t ed25519 -a 100 -q -N ''  -C root@{{ ansible_hostname }}"
    # cmd: "ssh-keygen -t ed25519 -a 100 -f ~/.ssh/id_ed25519 -q -N ''  -C root@{{ ansible_hostname }}"
    creates: ~/.ssh/id_ed25519

- name: Creating .gitconfig for root
  template:
    src: users/gitconfig-root.j2
    dest: ~/.gitconfig
    owner: root
    group: root
    mode: 0644
