---
- name: Tasks for virtualisation type NA - assuming physical
  when:
    - ansible_virtualization_role == "host"
  block:

    - name: Installing lldpd package
      ansible.builtin.apt:
        name: lldpd
        state: latest
      notify: Starting lldpd

- name: Tasks for virtualisation type kvm
  when:
    - ansible_virtualization_role == "guest"
    - ansible_virtualization_type == "kvm"
  block:

    - name: Installing qemu-guest-agent package
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: latest
      notify: Starting qemu-guest-agent

- name: Tasks for virtualisation type vmware
  when:
    - ansible_virtualization_role == "guest"
    - ansible_virtualization_type == "vmware"
  block:

    - name: Installing open-vm-tools package
      ansible.builtin.apt:
        name: open-vm-tools
        state: latest
